name: Deploy Static Webservice

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Just print something
        run: ls
